// USER ACTION CONSTANTS
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM'
export const SET_JOINED_GAME = 'SET_JOINED_GAME'
export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_USER_OPPONENT = 'SET_USER_OPPONENT'
export const SET_IS_IN_GAME = 'SET_IS_IN_GAME'
export const SET_CURRENT_CHOICE = 'SET_CURRENT_CHOICE'

// GAME ACTION CONSTANTS
export const SET_PLAYERS_IN_ROOM = 'SET_PLAYERS_IN_ROOM'